name: GraalVM native tests

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: "latest"
          java-version: "17"
          components: "native-image"
      - name: Running test
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          gu --version
          native-image --version
          native-image --initialize-at-build-time=org.junit.jupiter.engine.config.InstantiatingConfigurationParameterConverter,org.junit.platform.launcher.core.LauncherConfig
          ./gradlew nativeTest

  workflow-notification:
    needs:
      - build
    if: always()
    uses: ./.github/workflows/reusable-workflow-notification.yml
    with:
      success: ${{ needs.build.result == 'success' }}
